version: '3.5'

networks:
  $HABIDAT_DOCKER_PREFIX-proxy:
    driver: bridge 
    name: $HABIDAT_DOCKER_PREFIX-proxy

volumes:
  vhost:
  html:
  dhparam:

services:  

  nginx:
    image: jwilder/nginx-proxy
    container_name: $HABIDAT_DOCKER_PREFIX-nginx
    restart: unless-stopped
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certs:ro      
      - ./user.conf:/etc/nginx/vhost.d/$HABIDAT_USER_SUBDOMAIN.$HABIDAT_DOMAIN
      - ./cors_map.conf:/etc/nginx/conf.d/cors_map.conf
      - ./cookies.conf:/etc/nginx/conf.d/cookies.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - $HABIDAT_DOCKER_PREFIX-proxy
    logging:
      options:
        max-size: 50m

$HABIDAT_LETSENCRYPT_DISABLE  nginx-letsencrypt-companion:
$HABIDAT_LETSENCRYPT_DISABLE    restart: unless-stopped
$HABIDAT_LETSENCRYPT_DISABLE    image: jrcs/letsencrypt-nginx-proxy-companion
$HABIDAT_LETSENCRYPT_DISABLE    container_name: $HABIDAT_DOCKER_PREFIX-letsencrypt
$HABIDAT_LETSENCRYPT_DISABLE    volumes:
$HABIDAT_LETSENCRYPT_DISABLE      - vhost:/etc/nginx/vhost.d  
$HABIDAT_LETSENCRYPT_DISABLE      - html:/usr/share/nginx/html 
$HABIDAT_LETSENCRYPT_DISABLE      - /var/run/docker.sock:/var/run/docker.sock:ro
$HABIDAT_LETSENCRYPT_DISABLE      - ./certificates:/etc/nginx/certs:rw
$HABIDAT_LETSENCRYPT_DISABLE    environment:
$HABIDAT_LETSENCRYPT_DISABLE      - NGINX_PROXY_CONTAINER=$HABIDAT_DOCKER_PREFIX-nginx
$HABIDAT_LETSENCRYPT_DISABLE      - DEFAULT_EMAIL=$HABIDAT_ADMIN_EMAIL
$HABIDAT_LETSENCRYPT_DISABLE    logging:
$HABIDAT_LETSENCRYPT_DISABLE      options:
$HABIDAT_LETSENCRYPT_DISABLE        max-size: 50m      
